Create a UI to Adding books to a list.
jchernandez87/Awesome-Books pull request #1
Opened 2021-07-05 21:42 UTC by jchernandez87

#Changes; 😃 

*Add a basic HTML design with two inputs and a submit button.
*When you click you submit the input values to an array of objects and to the local storage.
*Add a class with methods to loop through the array of objects and render them dynamically.
*Add method to add new objects and to delete them from the UI but not from the local storage.

P.S: Still we don't know how to delete from the local storage.

![](https://media3.giphy.com/media/jkSvCVEXWlOla/giphy.gif)

2021-07-05 22:36 UTC, mricanho requested changes
Hi  @jchernandez87 @IbrohimRasulov, 

Good job so far! 🔥🔥 You are following the gitflow and you had already style your app!

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] The main problem here is that you are not saving the new changes once you remove a book. For this, you need to create a function that updates the local storage, and applied the function when you add the new book and remove the book. You already have it but you put it in one class. 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

![almost there](https://user-images.githubusercontent.com/60631456/124522078-87adcc80-ddb7-11eb-85d1-20411bf4142f.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-05 22:36 UTC, mricanho commented on script.js
> +}
- [ ] [OPTIONAL] Instead of classes, use plain functions and remember that a function must do one thing and one thing only, if you granulate your functions the debugging will be super easy with console.log

2021-07-05 22:36 UTC, mricanho commented on script.js
> +  }
- [ ] [OPTIONAL] If you divide this class into two functions, you can use them independently.

2021-07-05 23:01 UTC, jchernandez87 commented on script.js
> +  }
> * [ ]  [OPTIONAL] If you divide this class into two functions, you can use them independently.

Sure !!!. I will try that. Thanks 😃

2021-07-05 23:01 UTC, jchernandez87 commented on script.js
> +}
> * [ ]  [OPTIONAL] Instead of classes, use plain functions and remember that a function must do one thing and one thing only, if you granulate your functions the debugging will be super easy with console.log

Ho sorry, I was using plain functions but then I see that for tomorrow we will need to refactor to classes so I decided to already use classes. 😃

2021-07-06 21:36 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @jchernandez87 @IbrohimRasulov  🔥 

You worked hard in all the instructions that I previously give you👍🏽 

![doing good](https://user-images.githubusercontent.com/60631456/124669574-3d405480-de78-11eb-82fd-ef417b1e0432.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 21:37 UTC, merged